spring.application.name=serenazgo-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/serenazgo_bd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=hectorpalacios

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL del incident-service para comunicacion via RestTemplate
incident.service.url=http://localhost:8082